version: "2"
services:
  app:
    container_name: coolinference
    build:
      context: ../
      dockerfile: deployments/app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /app/    
